### ISSUE TITLE
Travis build error

### ISSUE THREAD

**Issue by evainga** [evainga/Timeline#1]
@mle-enso , 

as you can see I pushed everything to github. But my Travis doesn't build and I don't understand why. something with .mvnw...

```
3.01s$ ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

/home/travis/build.sh: line 218: ./mvnw: Permission denied

The command "eval ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V" failed. Retrying, 2 of 3.
```

Can you please have a look?

**Comment by mle-enso** [comment]
Strange, in line #140 of the Travis build console log, it reads

> $ ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

But the script in .travis.yml says

> script: mvn clean test

I'll take a deeper look into this. On my local machine everything is fine with mvn clean test

**Comment by mle-enso** [comment]
Apparently you ran into this one
https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
I've skipped this default install phase which occurs because of the <packaging>jar</packaging> in your pom.xml.
In your last Maven projects this 'problem' did not occur, because you defined no packaging information in your pom.xml
